bootstrap:
  queries:
    shop_information:
      create_table:
        - CREATE TABLE IF NOT EXISTS shop_information (
        -   id mediumint NOT NULL AUTO_INCREMENT,
        -   owner varchar(16) NOT NULL,
        -   location text DEFAULT NULL,
        -   description text DEFAULT NULL,
        -   created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        -   KEY id(id),
        -   PRIMARY KEY(owner)
        - );
      update:
        - replace into shop_information(owner, location, description) values (?, ?, ?)
      get_by_owner:
        - select * from shop_information where owner=?
      get_all:
        - select * from shop_information

    shop_transaction:
      create_table:
        - CREATE TABLE IF NOT EXISTS shop_transaction(
        -   shopId mediumint NOT NULL
        - );

view:
  shop:
    item_base:
      displayname: "Loja do %player_name%"
      lore:
        - "%battleshop_message_short%"
        - "Battle"